#!/bin/sh
set -eu

# Generated by bam-qc-flow 0.2.0-r1 at 2026-06-13T14:35:54Z
# Re-run from a shell with the same input paths and TAFFISH dependency commands available.

'taf-samtools-v1.23.1-r1' samtools quickcheck -v 'example-out/02_intermediate/bam_links/tiny/tiny.bam' && printf 'ok\n' > 'example-out/03_results/samtools/quickcheck/tiny.quickcheck.txt'
'taf-samtools-v1.23.1-r1' samtools flagstat -@ '1' 'example-out/02_intermediate/bam_links/tiny/tiny.bam' > 'example-out/03_results/samtools/flagstat/tiny.flagstat.txt'
'taf-samtools-v1.23.1-r1' samtools stats -@ '1' 'example-out/02_intermediate/bam_links/tiny/tiny.bam' > 'example-out/03_results/samtools/stats/tiny.stats.txt'
'taf-samtools-v1.23.1-r1' samtools idxstats -@ '1' 'example-out/02_intermediate/bam_links/tiny/tiny.bam' > 'example-out/03_results/samtools/idxstats/tiny.idxstats.tsv'
'taf-samtools-v1.23.1-r1' samtools coverage 'example-out/02_intermediate/bam_links/tiny/tiny.bam' > 'example-out/03_results/samtools/coverage/tiny.coverage.tsv'
'taf-mosdepth-v0.3.14-r2' mosdepth -n --fast-mode 'example-out/03_results/mosdepth/genome/tiny.genome' 'example-out/02_intermediate/bam_links/tiny/tiny.bam'
'taf-mosdepth-v0.3.14-r2' mosdepth -n --by 'bam-qc-flow/test-real-run-fixture/targets.bed' --thresholds 1,10,20,30 'example-out/03_results/mosdepth/regions/tiny.regions' 'example-out/02_intermediate/bam_links/tiny/tiny.bam'
'taf-multiqc-v1.35-r2' multiqc 'example-out/03_results' --outdir 'example-out/04_reports' --data-format json --force --title BAM_QC_example --filename multiqc_report.html
