#!/bin/sh
set -eu

# Generated by ngs-qc-flow 0.2.0-r1 at 2026-06-13T12:48:52Z
# Re-run from a shell with the same input paths and TAFFISH dependency commands in PATH.

taf-seqkit-v2.13.0-r2 sh 'example-out/02_intermediate/step_scripts/raw_seqkit_stats.sh'
# real command: seqkit stats -T -j '4' -a 'ngs-qc-flow/testdata/P1_R1.fastq' 'ngs-qc-flow/testdata/P1_R2.fastq' 'ngs-qc-flow/testdata/S2.fastq' > 'example-out/03_results/raw_seqkit/raw_fastq_stats.tsv'
taf-fastqc-v0.12.1-r1 sh 'example-out/02_intermediate/step_scripts/raw_fastqc.P1.sh'
# real command: fastqc --threads '4' --outdir 'example-out/03_results/raw_fastqc/P1' --quiet --nogroup 'ngs-qc-flow/testdata/P1_R1.fastq' 'ngs-qc-flow/testdata/P1_R2.fastq'
taf-fastqc-v0.12.1-r1 sh 'example-out/02_intermediate/step_scripts/raw_fastqc.S2.sh'
# real command: fastqc --threads '4' --outdir 'example-out/03_results/raw_fastqc/S2' --quiet --nogroup 'ngs-qc-flow/testdata/S2.fastq'
taf-fastp-v1.3.3-r3 sh 'example-out/02_intermediate/step_scripts/fastp.P1.sh'
# real command: fastp -i 'ngs-qc-flow/testdata/P1_R1.fastq' -I 'ngs-qc-flow/testdata/P1_R2.fastq' -o 'example-out/03_results/clean_fastq/P1_R1.clean.fastq.gz' -O 'example-out/03_results/clean_fastq/P1_R2.clean.fastq.gz' -h 'example-out/03_results/fastp/P1.fastp.html' -j 'example-out/03_results/fastp/P1.fastp.json' -w '4' --detect_adapter_for_pe --qualified_quality_phred '20' --length_required '15'
taf-fastp-v1.3.3-r3 sh 'example-out/02_intermediate/step_scripts/fastp.S2.sh'
# real command: fastp -i 'ngs-qc-flow/testdata/S2.fastq' -o 'example-out/03_results/clean_fastq/S2.clean.fastq.gz' -h 'example-out/03_results/fastp/S2.fastp.html' -j 'example-out/03_results/fastp/S2.fastp.json' -w '4' --qualified_quality_phred '20' --length_required '15'
taf-seqkit-v2.13.0-r2 sh 'example-out/02_intermediate/step_scripts/clean_seqkit_stats.sh'
# real command: seqkit stats -T -j '4' -a 'example-out/03_results/clean_fastq/P1_R1.clean.fastq.gz' 'example-out/03_results/clean_fastq/P1_R2.clean.fastq.gz' 'example-out/03_results/clean_fastq/S2.clean.fastq.gz' > 'example-out/03_results/clean_seqkit/clean_fastq_stats.tsv'
taf-fastqc-v0.12.1-r1 sh 'example-out/02_intermediate/step_scripts/clean_fastqc.P1.sh'
# real command: fastqc --threads '4' --outdir 'example-out/03_results/clean_fastqc/P1' --quiet --nogroup 'example-out/03_results/clean_fastq/P1_R1.clean.fastq.gz' 'example-out/03_results/clean_fastq/P1_R2.clean.fastq.gz'
taf-fastqc-v0.12.1-r1 sh 'example-out/02_intermediate/step_scripts/clean_fastqc.S2.sh'
# real command: fastqc --threads '4' --outdir 'example-out/03_results/clean_fastqc/S2' --quiet --nogroup 'example-out/03_results/clean_fastq/S2.clean.fastq.gz'
taf-multiqc-v1.35-r2 multiqc 'example-out/03_results' --outdir 'example-out/04_reports' --data-format json --force --title ngs-qc-real-run --filename multiqc_report.html
