#!/bin/sh
set -eu

# Generated by phylogeny-flow 0.1.0-r1 at 2026-05-28T17:32:41Z
# Commands are provenance records. Re-run from a shell with the same input paths and TAFFISH dependency commands in PATH.

taf-seqkit-v2.13.0-r2 seqkit stats -T 'cytc-out/02_intermediate/sequences.safe.fa' > 'cytc-out/00_inputs/input_seqkit_stats.tsv'
taf-mafft-v7.525-r3 mafft --auto --thread '6' 'cytc-out/02_intermediate/sequences.safe.fa' > 'cytc-out/02_intermediate/alignment.raw.fa'
taf-trimal-v1.5.1-r1 trimal -in 'cytc-out/02_intermediate/alignment.raw.fa' -out 'cytc-out/02_intermediate/alignment.trimmed.fa' -automated1
taf-iqtree-v3.1.2-r1 iqtree3 -s 'cytc-out/02_intermediate/alignment.trimmed.fa' -m 'LG' -T '6' --seed '20260528' --redo --prefix 'cytc-out/02_intermediate/tree_work/iqtree/iqtree'
taf-bioconductor-bioviz-v3.23-r2 bioviz-tree --tree 'cytc-out/03_results/tree/tree.nwk' --label-map 'cytc-out/00_inputs/sequence_id_map.tsv' --label-map-from safe_id --label-map-to original_id --layout 'rectangular' --formats 'pdf,png,svg' --style 'journal' --label-align 'none' --label-transform 'pretty' --scale-bar 'auto' --title 'phylogeny-flow tree - rectangular' --outdir 'cytc-out/03_results/tree/plots/rectangular'
taf-bioconductor-bioviz-v3.23-r2 bioviz-tree --tree 'cytc-out/03_results/tree/tree.nwk' --label-map 'cytc-out/00_inputs/sequence_id_map.tsv' --label-map-from safe_id --label-map-to original_id --layout 'circular' --formats 'pdf,png,svg' --style 'journal' --label-align 'none' --label-transform 'pretty' --scale-bar 'auto' --title 'phylogeny-flow tree - circular' --outdir 'cytc-out/03_results/tree/plots/circular'
